# Generated by Django 3.0.5 on 2020-05-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(choices=[('E', 'Entrada Dinero'), ('S', 'Salida Dinero')], default='S', max_length=1)),
                ('fechareg_mov', models.DateTimeField(blank=True, null=True)),
                ('fecha_mov', models.DateTimeField(blank=True, null=True)),
                ('importe_mov', models.FloatField()),
                ('descri_mov', models.CharField(max_length=50)),
            ],
        ),
    ]
